feat(core): details of syntax error on import
NeuraLegion/har-sdk pull request #102
Opened 2022-01-19 16:10 UTC by pmstss

closes #101

2022-01-24 09:38 UTC, derevnjuk requested changes

2022-01-24 09:38 UTC, derevnjuk commented on packages/core/src/loaders/errors/JsonSyntaxErrorDetailsExtractor.ts
> +    },
```suggestion
      positionExtractor: ([, possition]: RegExpMatchArray): ErrorPosition =>
        +possition
    },
```

2022-01-24 09:38 UTC, derevnjuk commented on packages/core/src/loaders/errors/JsonSyntaxErrorDetailsExtractor.ts
> +      })
```suggestion
      positionExtractor: ([, line, column]: RegExpMatchArray): ErrorPosition => ({
        lineNumber: +line,
        columnNumber: +column
      })
```

2022-01-24 09:38 UTC, derevnjuk commented on packages/core/src/loaders/errors/YamlSyntaxErrorDetailsExtractor.ts
> +      .replace(this.LOCATION_PATTERN, '')
Let's introduce a local variable

```suggestion
    const [someVarName]: string[] = error.message.split('\n');
    
    return someVarName
      .replace(/^YAMLException: /, '')
      .replace(this.LOCATION_PATTERN, '')
```

2022-01-24 09:38 UTC, derevnjuk commented on packages/core/src/loaders/errors/YamlSyntaxErrorDetailsExtractor.ts
> +    const matchRes = error.message.split('\n')[0].match(this.LOCATION_PATTERN);
ditto

2022-01-24 09:38 UTC, derevnjuk commented on packages/core/tests/JsonLoader.spec.ts
> +    })
We are not interested in the `SyntaxError` error itself, so we can rework output to verify the actual result of `getSyntaxErrorDetails `
```suggestion
    it(`should throw specific error for invalid input \`${input}\``, () => {
      (() => loader.load(input)).should.throw(SyntaxError);
      
      const result = loader.getSyntaxErrorDetails();
      
      result.should.deep.eq(output);
    })
```

2022-01-24 13:42 UTC, pmstss commented on packages/core/src/loaders/errors/BaseSyntaxErrorDetailsExtractor.ts
> +      ];
this potentially expensive calculation is done in lazy way because it's not always required: e. g. it will be used in ff+json & any+yaml cases, but not in chrome+json (& node+json) cases

2022-01-24 16:29 UTC, derevnjuk approved these changes

2022-01-24 16:29 UTC, derevnjuk commented on packages/core/tests/JsonLoader.spec.ts
> +    }
I don't think it is expected behavior if it raises an error while parsing valid JSON)

```suggestion
    loader.load('{"key": "value"}')
```

2022-01-24 16:29 UTC, derevnjuk commented on packages/core/tests/YamlLoader.spec.ts
> +    }
ditto

2022-01-25 07:53 UTC, derevnjuk approved these changes

2022-01-25 07:53 UTC, merged