refactor(oas): extract uri template logic
NeuraLegion/har-sdk pull request #135
Opened 2022-02-17 13:38 UTC by pmstss

relates-to #120

2022-02-17 13:39 UTC, pmstss commented
must be rebased after #134 merge

2022-02-17 16:10 UTC, pmstss commented
@derevnjuk complexity complains are caused by `PostDataConverter`, which refactoring we were decided to postpone;
is ready for review, but must be rebased after https://github.com/NeuraLegion/har-sdk/pull/134 merge

2022-02-17 17:18 UTC, derevnjuk reviewed
Let's rebase it first, and then I can continue the review. Currently, it appears to be not an easy task)

2022-02-17 17:18 UTC, derevnjuk commented on packages/oas/src/converter/parts/SubConvertersFactory.ts
> +  private subConverters = new Map<SubPart, SubConverter<unknown>>();
```suggestion
  private readonly subConverters = new Map<SubPart, SubConverter<unknown>>();
```

2022-02-17 17:18 UTC, derevnjuk commented on packages/oas/src/converter/parts/SubConvertersFactory.ts
> +  }
It looks like a registry, but not a factory) Let's rename accordinaly

2022-02-21 10:27 UTC, derevnjuk requested changes

2022-02-21 10:27 UTC, derevnjuk commented on packages/oas/src/converter/parts/SubConvertersRegistry.ts
> +        return this.createQueryStringConverter();
```suggestion
      case SubPart.QUERY_STRING:
        return this.createQueryStringConverter();
      default:
        throw new TypeError(`${type} subconverter is not supported`)
```

2022-02-21 10:27 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +  }
```suggestion
  protected createApiKeyHeader(scheme: SecuritySchemeApiKey): Header {
    return this.createHeader(scheme.name, 'REPLACE_KEY_VALUE');
  }

  protected createHeader(name: string, value: string): Header {
    return {
      value,
      name: name.toLowerCase()
    };
  }
```

2022-02-21 10:27 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +    return this.createHeader('authorization', 'Bearer REPLACE_BEARER_TOKEN');
Why don't use the sampler here?

```suggestion
    const token = this.sampler.sample({ type: 'string', maxLength: 10, minLength: 5 });
    
    return this.createHeader('authorization', `Bearer ${token}`);
```

2022-02-21 10:27 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +    return this.createHeader('authorization', 'Basic REPLACE_BASIC_AUTH');
ditto

2022-02-21 10:27 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +    return this.createHeader(scheme.name.toLowerCase(), 'REPLACE_KEY_VALUE');
ditto

2022-02-21 10:27 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/Oas3HeadersConverter.ts
> +    if (requestBody?.content != null && isObject(requestBody?.content)) {
```suggestion
    if (requestBody?.content && isObject(requestBody?.content)) {
```

2022-02-21 10:27 UTC, derevnjuk commented on packages/oas/src/converter/parts/path/Oas2PathConverter.ts
> +  private oas2ValueSerializer = new Oas2ValueSerializer();
```suggestion
  private readonly oas2ValueSerializer = new Oas2ValueSerializer();
```

2022-02-21 16:30 UTC, derevnjuk approved these changes

2022-02-21 16:32 UTC, merged