fix(oas): handling header parameters options
NeuraLegion/har-sdk pull request #136
Opened 2022-02-17 19:47 UTC by pmstss

fixes #120

2022-02-17 19:48 UTC, pmstss commented
wip (todo: oas2); should be rebased after #135 merge

2022-02-21 12:44 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/Oas3HeadersConverter.ts
> +    return [];
I suggest you provide an implementation for this method

```suggestion
    const responses = pathObj.responses as OpenAPIV3.ResponsesObject;
    
    if (isObject(responses)) {
     const code = Math.min(...Object.keys(responses))
    
      return this.createHeaders(
        'accept',
        Object.keys(responses[code].content)
      );
    }

    return [];
```

2022-02-21 17:47 UTC, pmstss commented
@derevnjuk now rebased)

2022-02-21 17:56 UTC, derevnjuk requested changes

2022-02-21 17:56 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/Oas2HeadersConveter.ts
> +    };
Use `createHeader()` where it is possible

```suggestion
    return this.createHeader(
      headerParam.param.name,
      this.oas2ValueSerializer.serialize(headerParam) as string
    );
```

2022-02-21 17:56 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/Oas3HeadersConverter.ts
> +    };
ditto

2022-02-21 18:18 UTC, derevnjuk approved these changes

2022-02-21 18:19 UTC, merged