test: migrate existing tests to jest
NeuraLegion/har-sdk pull request #144
Opened 2022-05-04 14:03 UTC by denis-maiorov-brightsec

2022-05-04 16:11 UTC, derevnjuk requested changes
1. Use `toMatchObject` where it is possible

Before:
```ts
// ...
expect(har).toHaveProperty('log.entries[0].response.status', 200);
expect(har).toHaveProperty('log.entries[0].response.content.size', 4);
// ...
```
After:
```ts
expect(har).toMatchObject({
  log: {
    entries: [
      {
        request: {
          url,
          method: 'GET',
          headers: [{ name: 'host', value: 'localhost:8000' }]
        },
        response: {
          status: 200,
          content: { size: 4, mimeType: 'text/plain', text: 'body' }
        }
      }
    ]
  }
});
```
2. Use `expect(result).toBeUndefined()` instead of `expect(typeof result).toEqual('undefined')`
3. You have to test specific expection where it is neccessary
Original:

```ts
(() => parseUrl(input)).should.throw('Invalid URL');
```

Incorrect:

```ts
expect(() => parseUrl(input)).toThrowError(Error);
```

Correct:

```ts
expect(() => parseUrl(input)).toThrowError('Invalid URL');
```

In case when you expect some instance of the derived class, just put a couple of assertions:

```ts
expect(() => parseUrl(input)).toThrowError('Invalid URL');
expect(() => parseUrl(input)).toThrowError(TypeError);
```

2022-05-05 08:14 UTC, denis-maiorov-brightsec commented on packages/editor/tests/oas2.spec.ts
> +        expect(typeof result).toBe('string');
It actually doesn't work:
```
 expect(received).toBeInstanceOf(expected)

    Expected constructor: String

    Received value has no prototype
    Received value: "lorem"
```

I think we should stick to typeof check bc imo using String constructor to construct string complicates things and should never be used

2022-05-05 08:20 UTC, derevnjuk commented on packages/editor/tests/oas2.spec.ts
> +        expect(typeof result).toBe('string');
Yeah, you are right. It won't work with primitives

2022-05-05 09:43 UTC, derevnjuk requested changes
BTW Let's create a root `jest.config.js` as follows:

```js
module.exports = {
  "projects": ["<rootDir>/packages/*"]
};
```

2022-05-05 09:43 UTC, derevnjuk commented on packages/validator/tsconfig.spec.json
> +}
You don't need to create a dedicated `tsconfig.spec.json`,  `tsconfig.json` already includes tests by default

2022-05-05 09:43 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +      expect(result).toMatchObject([]);
Please fix the same issue in other places as well

```suggestion
      expect(result).toEqual([]);
```

2022-05-05 09:59 UTC, derevnjuk commented on .eslintignore
> +**/jest.config.js
New line at end of the file is expected)

2022-05-05 10:01 UTC, derevnjuk commented on package.json
> +    "coverage:all": "lerna run coverage",
```suggestion
    "coverage:all": "jest --converage",
```

2022-05-05 10:42 UTC, derevnjuk reviewed
Please keep in mind as soon as we changed the reports folder, CI wouldn't upload them to CC anymore.

You have to update path to reports here:

https://github.com/NeuraLegion/har-sdk/blob/f5be7ae58a5720be8f6a0a8bff7df6556f428f41/.github/workflows/auto-build.yml#L69-L73

2022-05-06 13:18 UTC, derevnjuk requested changes
You have to revert package-lock.json, install npm@6 and update install deps again. The expected version is v1, we are not going to migrate to v2 within this PR)

2022-05-06 13:18 UTC, derevnjuk commented on packages/core/tests/YamlLoader.spec.ts
> +    expect(() => loader.load(input)).toThrowError(YAMLException);
```suggestion
    expect(() => loader.load(input)).toThrowError(YAMLException);
    expect(() => loader.load(input)).toThrowError(expectedExceptionMessage);
```

2022-05-06 15:06 UTC, derevnjuk approved these changes

2022-05-06 15:08 UTC, merged