fix(oas): updated converting when security is empty object and securitySchema is not exists
NeuraLegion/har-sdk pull request #168
Opened 2023-01-18 14:22 UTC by brightAMasiuk

fixes #167

2023-01-18 21:25 UTC, derevnjuk requested changes

2023-01-18 21:25 UTC, derevnjuk commented on packages/oas/tests/fixtures/params-security.oas.yaml
> +        - {}
You have made modifications to the base class, but this particular case, which allows for optional security requirements (i.e. `{}` in the list), is only supported by OAS3. To cover the rest of the cases, you will need to use the Swagger specification.

2023-01-18 21:25 UTC, derevnjuk commented on packages/oas/tests/fixtures/params-security.oas.yaml
> +        - Bearer: []
It would be nice to cover the remaining cases by combining security requirements with logical OR and AND operators as follows:
```yaml
security:    # A OR B
  - A
  - B
security:    # A AND B
  - A
    B
```

2023-01-18 21:25 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +  private getAuthHeaders(
```suggestion
  private createAuthHeaders(
```

2023-01-18 21:25 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
>          examples: Object.keys(obj)
There is another bug. When a security requirement includes multiple named security schemes, they must be combined using logical AND and applied simultaneously in the same request.

2023-01-18 21:25 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +        securitySchemes[schemeName] &&
Instead of using logic operators to control access to objects, the preferred way is to use the ternary operator.

2023-01-23 21:55 UTC, derevnjuk requested changes

2023-01-23 21:55 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +    console.log(headers);
`console.log` is strictly forbidden. To enforce this, there is an ESlint rule. It's important to understand why it is there.

2023-01-23 21:55 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +    return this.combineAuthHeaders(headers);
Well, the original comment is not resolved properly (https://github.com/NeuraLegion/har-sdk/pull/168#discussion_r1080567306). Moreover, you have introduced a dozen new bugs: it appears that the combining headers will lead to a NPE in the target scenario, while headers do not satisfy security schema at all.

2023-01-23 21:55 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +          headers.map((header) => header.value).join(', ')
This is totally wrong. The authorization HTTP header does not accept a comma separated list of values. Please refer to the RFC: tools.ietf.org/html/rfc7235#appendix-C 

2023-01-23 21:55 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
>        const schemeName = this.sampler.sample({
Why do you use the `sample`? The `schemaName` and `securityIndex` are always equal in this particular case.

2023-01-23 21:55 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +    Object.keys(securityRequirement).forEach((securityIndex) => {
Why not use `Object.entries` and `.map` instead of `Object.keys` and `.forEach` accordingly?

2023-01-24 09:11 UTC, pmstss commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +          headers.map((header) => header.value).join(', ')
also it could combine headers with different names (e. g. of `apiKey` security scheme type) into single (invalid) `authorization`

2023-01-25 07:29 UTC, pmstss requested changes

2023-01-25 12:38 UTC, pmstss requested changes

2023-01-25 12:38 UTC, pmstss commented on packages/oas/tests/fixtures/scheme-security-override.oas.yaml
> +          Bearer: {}
please validate and fix with `@har-sdk/validator`

2023-01-25 12:38 UTC, pmstss commented on packages/oas/tests/fixtures/scheme-security.oas.yaml
> +          description: Security schema key-query is not exists in securitySchemes
```suggestion
          description: Reference to non-existing security schema
```

2023-01-26 06:48 UTC, derevnjuk requested changes

2023-01-26 06:48 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +    for (const [schemeName] of Object.entries(securityRequirement)) {
```suggestion
    for (const schemeName of Object.keys(securityRequirement)) {
```

2023-01-26 06:48 UTC, derevnjuk commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +      headers.push(header);
Now the `headers` may contain an `undefined` value, which could potentially cause a null reference exception (NPE) and unexpected behavior.

2023-01-26 10:55 UTC, derevnjuk approved these changes

2023-01-26 12:53 UTC, pmstss commented on packages/oas/tests/fixtures/scheme-security.oas.yaml
> +openapi: 3.0.1
@derevnjuk shouldn't oas2 swagger specs b added too?

2023-02-01 07:05 UTC, derevnjuk commented on packages/oas/tests/fixtures/scheme-security.oas.yaml
> +  /pets/security-schema-is-not-exists:
It makes sense. However, currently, this does not represent any interest in the HAR-generating process. I suggest opening a separate ticket for this matter (will be done out of the regular process).

2023-02-01 07:11 UTC, derevnjuk commented on packages/oas/tests/fixtures/scheme-security.oas.result.json
> +    "url": "https://petstore.swagger.io/pets/security-empty-and-bearer"
For more complete coverage and to ensure all relevant information is included, I propose utilizing security claims according to the rules mentioned at https://github.com/NeuraLegion/har-sdk/pull/168#discussion_r1080558459, even if they are not mandatory.

> "and" in naming is not correct - actually it's "one of" case

I agree, this is a bit confusing.

2023-02-01 07:12 UTC, derevnjuk commented on packages/oas/tests/fixtures/scheme-security.oas.yaml
> +openapi: 3.0.1
Yeah, as was mentioned in the conversation at https://github.com/NeuraLegion/har-sdk/pull/168#discussion_r1080554321

2023-02-07 06:02 UTC, derevnjuk approved these changes

2023-02-07 07:12 UTC, pmstss approved these changes

2023-02-07 07:16 UTC, merged