feat(editor): introduce schema editor
NeuraLegion/har-sdk pull request #21
Opened 2021-10-27 15:42 UTC by pmstss

closes #20

2021-11-08 11:40 UTC, derevnjuk requested changes

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/editor/postman/PostmanBodyParser.ts
> +      valueJsonPointer: pointer
```suggestion
      bodyType,
      value,
      paramType: 'requestBody',
      valueJsonPointer: pointer
```

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/models/HttpMethod.ts
> +export function isHttpMethod(method: string): boolean {
```suggestion
export function isHttpMethod(method: string): method is HttpMethod {
```

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/models/tree/SpecTreeNode.ts
> +  readonly parameters?: ReadonlyArray<SpecTreeNodeParam>;
Misconfigured `eslint` rules) Optional fields must be placed last

```suggestion
  readonly jsonPointer: string;
  readonly name?: string;
  readonly method?: HttpMethod;
  readonly children?: ReadonlyArray<SpecTreeNode>;
  readonly parameters?: ReadonlyArray<SpecTreeNodeParam>;
```

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/models/tree/SpecTreeNodeParam.ts
> +  readonly valueJsonPointer: string;
ditto

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/editor/oas/BaseOasEditor.ts
> +  protected dereferencedDoc: D;
```suggestion
  protected dereferencedDoc: D | undefined;
```

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/editor/oas/BaseOasParameterObjectsParser.ts
> +  ) {}
I suggest raising an exception if `doc` or `dereferencedDoc` are not defined. It says us that library's user forget to call `setup`

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/editor/oas/BaseOasPathItemObjectParser.ts
> +  protected constructor(protected readonly doc: D) {}
ditto

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/editor/oas/v2/OasV2OperationObjectParser.ts
> +  }
ditto

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/editor/oas/v2/OasV2PathItemObjectParser.ts
> +  }
ditto

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/src/editor/oas/v3/OasV3OperationObjectParser.ts
> +  }
ditto

2021-11-08 11:40 UTC, derevnjuk commented on packages/editor/tests/oas2.spec.ts
> +    it('should be exception on invalid syntax', async () =>
```suggestion
    it('should be exception on invalid syntax', () =>
```

2021-11-08 17:05 UTC, pmstss commented on packages/editor/src/editor/oas/BaseOasEditor.ts
> +    }
didn't get an idea. if `refJsonPointer` is undefined - no need to dereference via `.set()`

2021-11-08 19:13 UTC, derevnjuk commented on packages/editor/src/editor/oas/BaseOasEditor.ts
> +    }
Never mind,  I just imagined the whole thing.

2021-11-08 19:52 UTC, derevnjuk requested changes
The last comments relate to all tests some of them we can skip for now

2021-11-08 19:52 UTC, derevnjuk commented on packages/editor/tests/oas2.spec.ts
> +  });
I would split integration and unit tests. Anyway, we can do that later

2021-11-08 19:52 UTC, derevnjuk commented on packages/editor/tests/oas2.spec.ts
> +  describe('oas v2 tree parser', () => {
That should allow you to avoid duplicating preparation steps

```ts
describe('oas v2 tree parsing', () => {
  let openApiParser: TreeParser;

  beforeEach(() => {
    openApiParser = new OasV2Editor();

    return openApiParser.setup(source)
  });

  it('should correctly parse yaml valid document', () => {
      const tree = openApiParser.parse();

      tree.should.deep.eq(resultTree);
    });
});
```

2021-11-08 19:52 UTC, derevnjuk commented on packages/editor/tests/oas2.spec.ts
> +          /Bad Swagger\/OpenAPI V2 specification/
As far as I know you can use a string as well
```suggestion
          'Bad Swagger/OpenAPI V2 specification'
```

2021-11-08 19:52 UTC, derevnjuk commented on packages/editor/tests/oas2.spec.ts
> +      tree.parameters[0].value.should.eq('petstore.swagger.io');
Assert on the entire object, not on every field. It's important from the test report perspective since we want to desire a result as a single unit, like a story.

```suggestion
      tree.should.deep.equal({ parameters: ['petstore.swagger.io'] });
```

2021-11-08 19:52 UTC, derevnjuk commented on packages/editor/tests/oas2.spec.ts
> +        let tree = openApiEditor.parse();
ditto

2021-11-08 19:52 UTC, derevnjuk commented on packages/editor/tests/oas2.spec.ts
> +        ]);
Use the AAA pattern to organize your tests.
```suggestion
        const input = 'neuralegion.com';
        
        const result = openApiEditor.setParameterValue(
          tree.parameters[0].valueJsonPointer,
          newValue
        );

        result.parameters.should.deep.equal([
          {
            paramType: 'variable',
            name: 'host',
            valueJsonPointer: '/host',
            value: newValue
          }
        ]);
```

2021-11-08 19:52 UTC, derevnjuk commented on packages/editor/tests/oas2.spec.ts
> +        shouldBeValidDoc(openApiEditor['doc']);
I'm totally again the idea assert the result using private or internal staff. Use the public API to assert the new data. It is more convenient and reduces the risk to rework tests while changing the implementation.

2021-11-08 19:52 UTC, derevnjuk commented on packages/editor/tests/oas3.spec.ts
> +        await openApiEditor.setup(source);
Extract preparation step to `beforeEach`. In addition, it would be better to create a new instance of `Editor` before each tests.

2021-11-08 19:52 UTC, derevnjuk commented on packages/editor/tests/oas3.spec.ts
> +        openApiEditor.stringify().should.match(/^openapi:/);
Declare a local variable to avoid multiple calls
```suggestion
        const result = openApiEditor.stringify();
        result.should.be.a('string').and.match(/^openapi:/);
```

2021-11-09 07:28 UTC, pmstss commented on packages/editor/src/editor/oas/BaseOasEditor.ts
> +  }
cache of already "identified" `$ref` pointers? but this is one time job - on first call of `setParameterValue()` for specific referenced parameter. on the first call it will be "dereferenced" and no more `getRefJsonPointer()` calls will be made on further calls of `setParameterValue()` for the same parameter

2021-11-09 07:33 UTC, pmstss commented on packages/editor/src/editor/oas/BaseOasParameterObjectsParser.ts
> +  ) {}
- but all these referenced constructors are part of private API. this check - if required - imo should be done in public `setParameterValue()`  and `removeNode()` calls. wdyt?
- referenced comment adds "parse() before stringify()" check. but we also have setup() here.  should check "setup() before parse()" be added too?

2021-11-09 10:02 UTC, pmstss commented on packages/editor/tests/oas2.spec.ts
> +      tree.parameters[0].value.should.eq('petstore.swagger.io');
this specific parameter test case will be removed as partial duplicate of previous one, where full tree (including that root-level parameters) is compared

2021-11-09 10:52 UTC, derevnjuk commented on packages/editor/src/editor/oas/BaseOasParameterObjectsParser.ts
> +  ) {}
> this check - if required - imo should be done in public

That makes sense, it will also work

> should check "setup() before parse()" be added too?

I guess so. We have to prevent any misuse of public API

2021-11-09 14:13 UTC, pmstss commented on packages/editor/src/editor/oas/BaseOasParameterObjectsParser.ts
> +  ) {}
introduced `validateParsedSource()` and `validateParsedTree()`

2021-11-09 14:13 UTC, pmstss commented on packages/editor/src/editor/oas/BaseOasPathItemObjectParser.ts
> +  protected constructor(protected readonly doc: D) {}
https://github.com/NeuraLegion/har-sdk/pull/21/#discussion_r745654205

2021-11-09 14:13 UTC, pmstss commented on packages/editor/src/editor/oas/v2/OasV2OperationObjectParser.ts
> +  }
https://github.com/NeuraLegion/har-sdk/pull/21/#discussion_r745654205

2021-11-09 14:13 UTC, pmstss commented on packages/editor/src/editor/oas/v2/OasV2PathItemObjectParser.ts
> +  }
https://github.com/NeuraLegion/har-sdk/pull/21/#discussion_r745654205

2021-11-09 14:13 UTC, pmstss commented on packages/editor/src/editor/oas/v3/OasV3OperationObjectParser.ts
> +  }
https://github.com/NeuraLegion/har-sdk/pull/21/#discussion_r745654205

2021-11-09 16:28 UTC, derevnjuk requested changes

2021-11-09 16:28 UTC, derevnjuk commented on packages/editor/src/editor/oas/BaseOasPathItemObjectParser.ts
> +      path,
`jsonPointer.parse(pointer).pop()` might return undefined if `pointer` refs to root. I don't think that might happen while regular flow, but anyway

2021-11-09 16:28 UTC, derevnjuk commented on packages/editor/src/editor/oas/BaseOasOperationObjectParser.ts
> +      path,
ditto

2021-11-09 16:28 UTC, derevnjuk commented on packages/editor/src/editor/oas/BaseOasParameterObjectsParser.ts
> +      : (parameter as OpenAPIV2.Parameter);
It seems `jsonPointer.get(this.dereferencedDoc, pointer)` will raise an exception if no such pointer. Is it intended?

2021-11-09 16:28 UTC, derevnjuk commented on packages/editor/src/editor/oas/v2/OasV2ParameterObjectsParser.ts
> +    return paramObj.default ?? paramObj?.items?.default;
I guess null coalescing operator is redundant

```suggestion
    return paramObj.default ?? paramObj.items?.default;
```

2021-11-09 16:28 UTC, derevnjuk commented on packages/editor/src/editor/BaseTreeParser.ts
> +  ): Promise<{ doc: T; format: 'yaml' | 'json' }> {
```suggestion
  ): Promise<{ doc: T; format: 'yaml' | 'json' } | undefined> {
```

2021-11-09 16:28 UTC, derevnjuk commented on packages/editor/src/editor/BaseTreeParser.ts
> +  }
I suggest you use `assertion` methods or just getter. That should improve the usage experience of the library

```ts
protected validateParsedTree(value: SpecTreeNode | undefined): asserts value is NonNullable<SpecTreeNode> {
    if (!value) {
      throw new Error('You have to call "parse" to initialize the tree');
    }
  }
```

or

```ts
private _tree: SpecTreeNode | undefined;

get tree(): SpecTreeNode {
  if (this._tree) {
    throw new Error('You have to call "parse" to initialize the tree');
  }

 return this._tree;
}
```

I would prefer to use `getter` since we can't guarantee that other developers will use assertion methods as expected.

2021-11-09 16:28 UTC, derevnjuk commented on packages/editor/src/editor/BaseEditor.ts
> +  }
Why don't use getter instead?

```suggestion
  public getDocument(): Readonly<T> | undefined {
    return this.doc;
  }
```

2021-11-09 16:28 UTC, derevnjuk commented on packages/editor/src/editor/postman/PostmanEditor.ts
> +          method: x.request.method.toUpperCase() as HttpMethod,
```suggestion
          method: x.request?.method.toUpperCase() as HttpMethod,
```

2021-11-09 17:42 UTC, pmstss commented on packages/editor/src/editor/oas/BaseOasPathItemObjectParser.ts
> +      path,
indeed root pointer as input is not the case for current internal usage like `pathItemObjectParser.parse(jsonPointer.compile(['paths', path]))`.
even in case of '/' - `jsonPointer.parse('/').pop()` is '', but in case of '' - it will be indeed `undefined`. 
do you see much sense in raising `Invalid path item JSON pointer` for the case `jsonPointer.parse(pointer).length < 2`?

2021-11-09 17:47 UTC, pmstss commented on packages/editor/src/editor/oas/BaseOasParameterObjectsParser.ts
> +      : (parameter as OpenAPIV2.Parameter);
`parseParameter` is internal (modifier can be changed to `private`), so input `pointer` is assumed to be valid one, and if there is nothing in `this.dereferencedDoc` for that pointer - well, exception is expected

2021-11-09 18:00 UTC, derevnjuk commented on packages/editor/src/editor/oas/BaseOasPathItemObjectParser.ts
> +      path,
If it returns '', it will be ok. I don't see any issue

2021-11-09 18:13 UTC, derevnjuk approved these changes

2021-11-09 18:14 UTC, merged