fix(oas): use `application/json` when `consumes` media-type configuration missing
NeuraLegion/har-sdk pull request #211
Opened 2023-09-18 15:48 UTC by ostridm

closes #210

2023-09-18 17:20 UTC, derevnjuk requested changes

2023-09-19 05:51 UTC, ostridm commented on packages/oas/tests/fixtures/params-form-data.swagger.result.json
> +        "value": "application/json"
This particular case has explicit root level `produces`, see below. Introduced default `*/*` value for missing `produces` configuration.

``` yaml
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json
paths:
  /example:
    post:
      operationId: addExample
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          type: file
          required: true
```

2023-09-20 10:45 UTC, pmstss requested changes

2023-09-20 10:45 UTC, pmstss commented on packages/oas/tests/fixtures/github.swagger.result.json
it's hard to check relevant changes especially in this 200KB file due to reordered properties; please rework fixtures result formatting to keep previous ordering

2023-09-21 07:21 UTC, ostridm commented on packages/oas/tests/fixtures/github.swagger.result.json
reworked, please proceed

2023-09-21 11:32 UTC, pmstss requested changes
thanks, looks good, please consider following improvement in addition to commented in code:
- please add explicit root level `consumes` fixture
- please add fixtures for `produces` cases (root-level, operation-level, overriding)

2023-09-21 11:32 UTC, pmstss commented on packages/oas/src/converter/parts/headers/HeadersConverter.ts
> +      )
```suggestion
      !headers.some(
        (header) => header.name.toLowerCase() === this.CONTENT_TYPE_HEADER
      )
```

2023-09-21 12:37 UTC, pmstss approved these changes

2023-09-21 13:24 UTC, derevnjuk approved these changes

2023-09-21 13:24 UTC, merged