feat(validator): humanized validation messages
NeuraLegion/har-sdk pull request #23
Opened 2021-11-03 17:13 UTC by pmstss

closes #22

2021-11-05 13:14 UTC, derevnjuk requested changes

2021-11-05 13:14 UTC, derevnjuk commented on packages/validator/src/validator/ErrorCondenser.ts
> +  private tree: Record<string, Record<string, ErrorObject[]>>;
```suggestion
  private tree?: Record<string, Record<string, ErrorObject[]>>;
```

2021-11-05 13:14 UTC, derevnjuk commented on packages/validator/src/validator/ErrorCondenser.ts
> +      (prev: ErrorObject, err: ErrorObject): ErrorObject =>
```suggestion
      (prev: ErrorObject | undefined, err: ErrorObject): ErrorObject =>
```

2021-11-05 13:14 UTC, derevnjuk commented on packages/validator/src/validator/ErrorCondenser.ts
> +    }
This is a redundant check, you can remove it.

2021-11-05 13:14 UTC, derevnjuk commented on packages/validator/src/validator/ErrorCondenser.ts
> +    this.parseToTree();
Why don't call this method in the constructor? Wdyt?

2021-11-05 13:40 UTC, derevnjuk commented on packages/validator/src/schemas/postman/v2.1.0.json
> +              }
I don't think we should allow users to specify custom methods

2021-11-05 13:40 UTC, derevnjuk commented on packages/validator/src/schemas/postman/v2.1.0.json
> +            "anyOf": [
Should we rework it using `if/else` keywords?

2021-11-05 13:43 UTC, derevnjuk commented on packages/validator/src/schemas/postman/v2.1.0.json
> +                    "anyOf": [
Should we rework it using `if/else` keyworks?

2021-11-05 13:43 UTC, derevnjuk commented on packages/validator/src/schemas/postman/v2.1.0.json
> +            "anyOf": [
Should we rework it using `if/else` keyworks?

2021-11-05 13:44 UTC, derevnjuk commented on packages/validator/src/schemas/postman/v2.0.0.json
> +              }
ditto

2021-11-05 13:58 UTC, derevnjuk requested changes

2021-11-05 13:58 UTC, derevnjuk commented on packages/validator/src/schemas/postman/v2.0.0.json
> +                    "anyOf": [
ditto

2021-11-05 13:58 UTC, derevnjuk commented on packages/validator/src/schemas/openapi/v3.0.0.json
> +      "required": ["name", "in"],
When `in: path`, `required` is required to be `true`. Is there any way to cover this case?

2021-11-05 14:05 UTC, derevnjuk commented on packages/validator/src/schemas/openapi/v2.0.0.json
> +      "required": ["name", "in", "type", "required"],
- By default only `in` and `name` fields are required. 
- `type` is required when `in` is not `body`. 
- `schema` must be required if `in` is `body`

Wdyt? Can we handle these constraints somehow?

2021-11-05 14:13 UTC, derevnjuk requested changes

2021-11-05 14:13 UTC, derevnjuk commented on packages/validator/src/schemas/postman/v2.0.0.json
> +        "type": ["string", "null"]
Should we extract `null` under `then` keyword?

2021-11-05 14:13 UTC, derevnjuk commented on packages/validator/src/schemas/postman/v2.0.0.json
> +            "type": ["string", "null"]
ditto

2021-11-05 14:23 UTC, derevnjuk requested changes

2021-11-05 14:23 UTC, derevnjuk commented on packages/validator/tests/error-condenser.spec.ts
> +  it('should condense duplicated errors', () => {
Put all tests under a single test suite (e.g. `describe('condense')`).

2021-11-05 14:23 UTC, derevnjuk commented on packages/validator/tests/error-condenser.spec.ts
> +  });
```suggestion
  it('should handle empty input', () => new ErrorCondenser(null).condense().should.be.empty);
```

2021-11-05 14:23 UTC, derevnjuk commented on packages/validator/tests/error-humanizer.spec.ts
> +  it('should return original "errorMessage" if exists', async () => {
ditto (e.g. `describe('humanizeErrors')`)

2021-11-05 14:23 UTC, derevnjuk commented on packages/validator/tests/error-humanizer.spec.ts
> +      .humanizeErrors(await oasValidator.verify(apiDoc))
To keep the test structure clean, I suggest using AAA pattern. Move `await oasValidator.verify(apiDoc)` under the arrange step.

```js
// arrange
const input = {};
const expected = {};

// act
const result = doSomething(input);

// assert
result.should.eq(input)
```

2021-11-05 15:10 UTC, pmstss commented on packages/validator/src/validator/ErrorCondenser.ts
> +      (prev: ErrorObject, err: ErrorObject): ErrorObject =>
seems invalid - as it's special case w/o "initialValue" (few lines latter we have e. g. `!prev.params`)

2021-11-05 15:16 UTC, pmstss commented on packages/validator/src/validator/ErrorCondenser.ts
> +    );
utilized `flatMap`

2021-11-05 15:50 UTC, pmstss commented on packages/validator/tests/error-condenser.spec.ts
> +  it('should condense duplicated errors', () => {
but they are already in `ErrorCondenser` suite; please clarify the idea of having one more nesting for suites

2021-11-05 22:44 UTC, derevnjuk commented on packages/validator/tests/error-condenser.spec.ts
> +  it('should condense duplicated errors', () => {
Just to have the following structure: `class -> method -> tests`. That provides a huge amount of benefits (e.g skipping all tests for particular method, removing them without of pain, easy navigation).

2021-11-08 15:16 UTC, pmstss commented on packages/validator/src/schemas/postman/v2.1.0.json
> +                    "anyOf": [
not really as "anyOf" validator messages are nearly good due to const restrictions on type for both branches; added minor fixes and tests

2021-11-08 15:37 UTC, pmstss commented on packages/validator/src/schemas/openapi/v2.0.0.json
> +      "required": ["name", "in", "type", "required"],
not sure that got your question correctly.

> type is required when in is not body.
> schema must be required if in is body (btw there is not schema def here)

this is reflected in `bodyParameter` declaration above; but this comment is linked to specific `pathParameterSubSchema`

2021-11-08 15:44 UTC, pmstss commented on packages/validator/src/schemas/openapi/v3.0.0.json
> +      "required": ["name", "in"],
seems it's already covered by `allOf` on next line + inner `allOf` of `ParameterLocation`:

```
        {
          "if": {
            "required": ["in"],
            "properties": {
              "in": {
                "const": "path"
              }
            }
          },
          "then": {
            "description": "Parameter in path",
            "required": ["in", "required"],  // <-- HERE
            "properties": {
              "in": {
                "const": "path"
              },
              "style": {
                "enum": ["matrix", "label", "simple"],
                "default": "simple"
              },
              "required": {
                "const": true // <-- HERE
              }
            }
          }
        }
```

2021-11-08 18:34 UTC, derevnjuk approved these changes

2021-11-08 19:01 UTC, merged