fix(sampler): able to sample pattern format with nested infinite quantifiers and max-length constraint
NeuraLegion/har-sdk pull request #247
Opened 2024-08-09 07:24 UTC by ostridm

closes #246

2024-08-13 10:34 UTC, derevnjuk requested changes

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
>      randExp.randInt = (a, b) => Math.floor((a + b) / 2);
It's unclear why `randInt` field is assigned the same value multiple times on the same instance

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +    return ['+', '*', ',}'].some((q) => pat.includes(q));
```suggestion
    return /(\+|\*|\{\d*,\})/.test(pattern.toString());
```

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +      randExp.max = lmax;
The loop is too complex, please streamline it as follow:

```suggestion
    for (let i = 1; i <= max; i++) {
      randExp.max = Math.floor(max / i);
```

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +    randExp.max = 0;
Try to generate with minimum length, and then if this fails, just double it

```suggestion
    randExp.max = min;
```

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
>      }
Inverse the condition to avoid duplicates like this:
```ts
if (result.length < min) {
  randExp.max = 2 * min;
  result = randExp.gen();
}
```

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +  private sampleMinLength(randExp: RandExp, min: number, max: number) {
```suggestion
  private sampleWithMinLength(randExp: RandExp, min: number, max: number) {
```

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +  private sampleMinLength(randExp: RandExp, min: number, max: number) {
You are passing `max` as an extra arg w/o any reason; streamline the flow by calling `adjustMaxLength` only within `patternSample` method (if possible)

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +      if (result.length <= max) {
Could we get in a situation when it will consistently generates strings longer than max? Seems we should add a maximum iteration limit. Let's test with some `Number.MAX_SAFE_INTEGER` and see

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +    const pat = pattern.toString();
`RegExp#toString()` and `pattern` keyword is not compatible 

```suggestion
    const pat = pattern.source;
```

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
>      if (min) {
Use more explicit undefined checks for min and max to avoid potential issues with 0. Here is example:
```suggestion
    if (min !== undefined) {
```

2024-08-13 10:34 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +    return !!max && result.length > max && this.hasInfiniteQuantifier(pattern)
ditto

2024-08-13 16:49 UTC, ostridm commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +  private sampleMinLength(randExp: RandExp, min: number, max: number) {
Unfortunately, `adjustMaxLength` applied only for doubled `min` 
Just in case, applying `adjustMaxLength` to the first probe will not fail controversial cases like 

```
{
  type: 'string',
  format: 'pattern',
  pattern: '^[a]+[b]+$',
  maxLength: 1,
  minLength: 1
}
```

2024-08-14 07:27 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +        `Sample string cannot be generated by boundaries: ${boundariesStr}`
The error message is unclear
```suggestion
        `Sample string cannot be generated by boundaries: ${boundariesStr}. Both minLength and maxLength must not exceed ${this.MAX_PATTERN_SAMPLE_LENGTH}`
`
```

2024-08-14 07:27 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +    );
The check is redundant; do not validate the schema

```suggestion
    return (
      boundary === undefined ||
      boundary <= this.MAX_PATTERN_SAMPLE_LENGTH
    );
```

2024-08-14 07:27 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +  private readonly MAX_PATTERN_SAMPLE_LENGTH = 500;
Add a code comment to explain a choice of 500

2024-08-14 10:22 UTC, derevnjuk approved these changes

2024-08-14 10:22 UTC, merged