Feat #2/har sdk implementation
NeuraLegion/har-sdk pull request #3
Opened 2021-04-21 08:51 UTC by mvhysko

2021-05-07 07:53 UTC, derevnjuk requested changes

2021-05-07 07:53 UTC, derevnjuk commented on package.json
> +    "@neuralegion/openapi-sampler": "^0.7.2",
Why is it part of deps?

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/README.md
> +**THIS REPO HAS BEEN DEPRECATED. THE DEVELOPMENT HAS MOVED TO A NEW REPOSITORY: https://github.com/NeuraLegion/har-recorder**
Remove this disclaimer

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/README.md
> +```
Rewrite examples using typescript.

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/package.json
> +    "tests": "cross-env TS_NODE_PROJECT=./tsconfig.spec.json mocha -r ts-node/register -r tsconfig-paths/register tests/**/*.spec.ts",
```suggestion
    "test": "cross-env TS_NODE_PROJECT=./tsconfig.spec.json mocha -r ts-node/register -r tsconfig-paths/register tests/**/*.spec.ts",
```

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/src/builder/DefaultHarBuilder.ts
> +import * as Request from 'request';
Don't use wildcard imports, you should explicitly import the things you want to use in a module

```suggestion
import HAR from 'har-format';
import request from 'request';
```

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/src/builder/DefaultHarBuilder.ts
> +      const boundary = header.split(' ')[1].split('=')[1];
Is it intended? Now it's quite hard to read this line

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/src/builder/DefaultHarBuilder.ts
> +      // boundary = boundary.split("=")[1]
Remove useless comments

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/src/builder/DefaultHarBuilder.ts
> +        // text: this.convertFormDataToText(params, boundary)
It's not clear, why did you remove this line?

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/src/builder/DefaultHarBuilder.ts
> +    } catch (e) {
```suggestion
    } catch {
```

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/src/capture/DefaultCapture.ts
> +    dnsCache: Record<string, string> = {},
Obviously, you don't need to pass `dnsCache` through methods (use instance member).

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/src/index.ts
> +import pkg from '../../../package.json';
Why use root package.json?

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/src/index.ts
> +  const capture: Capture = new DefaultCapture(builder, parser);
```suggestion
  const builder = new DefaultHarBuilder(parser);
  const capture = new DefaultCapture(builder, parser);
```

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/tests/captureHar.spec.ts
> +    // assert.notNestedPropertyVal(har, 'log.entries[0].response._error.stack');
ditto

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/tests/captureHar.ts
> +console.log(validateHar);
ditto

2021-05-07 07:53 UTC, derevnjuk commented on packages/capture/src/types/capture.ts
> +export declare namespace CaptureHar {
You should use ambient declarations instead

2021-05-11 08:18 UTC, derevnjuk commented on packages/oas/src/converter/Converter.ts
> +import { OAS } from '../types/oas';
You can refuse using `types` if you install `openapi-types`

2021-05-11 08:20 UTC, derevnjuk commented on packages/oas/src/converter/DefaultConverter.ts
> +          } catch (err) {
```suggestion
          } catch {
```

2021-05-11 08:23 UTC, derevnjuk commented on packages/oas/src/loader/DefaultLoader.ts
> +import { readFile } from 'fs/promises';
Don't use `fs/promises` module since it is available only in Node.js v15

2021-05-11 08:23 UTC, derevnjuk commented on packages/oas/src/loader/DefaultLoader.ts
> +    if (['.yml', '.yaml'].includes(ext)) {
```suggestion
    const ext: string = extname(path);
    const content: string = await this.read(path);

    if (['.yml', '.yaml'].includes(ext.toLowerCase())) {
```

2021-05-11 08:24 UTC, derevnjuk commented on packages/oas/src/loader/DefaultLoader.ts
> +    if (['.yml', '.yaml'].includes(ext)) {
Extract this list to read-only instance property

2021-05-11 08:25 UTC, derevnjuk commented on packages/oas/src/types/jstoxml/index.d.ts
> +declare module 'jstoxml' {
Don't use `types` folder for ambient declarations, use `typings`

2021-05-11 08:27 UTC, derevnjuk commented on packages/oas/src/types/openapi-sampler/index.d.ts
> +declare module '@neuralegion/openapi-sampler' {
What is the reason to declare `d.ts` for a package which already providers type declaration?

2021-05-11 08:32 UTC, derevnjuk commented on packages/oas/src/utils/Flattener.ts
> +export class Flattener {
Utility class is code smell, don't use them. Moreover, `flattenConfig` looks odd. Why don't use instantiated classes?

2021-05-11 08:32 UTC, derevnjuk commented on packages/oas/src/utils/StringHelper.ts
> +export class StringHelper {
You can declare helper classes for such methods, but they shouldn't contain business logic.

2021-05-11 08:35 UTC, derevnjuk commented on packages/oas/src/utils/Versioning.ts
> +export class Versioning {
ditto

2021-05-11 08:37 UTC, derevnjuk commented on packages/oas/src/utils/resolveRef.ts
> +  spec: Record<string, any>,
Avoid using `any`, the preferred way is `unknown`

```suggestion
  spec: Record<string, unknown>,
```

2021-05-11 08:40 UTC, derevnjuk commented on packages/openapi-sampler/src/index.ts
> +import { Sampler } from './samplers/Sampler';
Create barrel file (aka `index.ts`) to organize imports

2021-05-11 08:43 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/Sampler.ts
> +export interface ISampler {
Don't use `I*` prefixes with interfaces.

2021-05-11 08:43 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/Sampler.ts
> +export abstract class Sampler {
I don't see any reason why we should declare an abstract class.

2021-05-11 08:45 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +function emailSample() {
Use arrow functions instead

2021-05-11 08:50 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/StringSampler.ts
> +};
You can declare an interface and implement it (See `Generators` in `postman2har`)

2021-05-14 11:42 UTC, derevnjuk requested changes

2021-05-14 11:42 UTC, derevnjuk commented on .github/workflows/auto-build.yml
> +      - run: npx lerna bootstrap --hoist
Never use `npx` in CI when you have the same package in `package.json`

2021-05-14 11:42 UTC, derevnjuk commented on .github/workflows/auto-build.yml
> +      - run: npx lerna run test
```suggestion
      - run: npx lerna run format:changed
      - run: npx lerna run lint:changed
      - run: npx lerna run build:changed
      - run: npx lerna run test:changed
```

2021-05-14 11:42 UTC, derevnjuk commented on packages/capture/tsconfig.spec.json
> +{
We agreed to place `tsconfig.json` for specs into `tests` folder

2021-05-14 11:42 UTC, derevnjuk commented on packages/openapi-sampler/tests/integration.spec.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
```suggestion
```

2021-05-14 11:42 UTC, derevnjuk commented on packages/openapi-sampler/tests/integration.spec.ts
> +describe('Integration', () => {
Please split this huge file into multiple specs

2021-05-14 11:42 UTC, derevnjuk commented on packages/openapi-sampler/tests/integration.spec.ts
> +    // it('should ignore readOnly params if referenced', () => {
Remove redundant comments or use `skip`

2021-05-14 11:42 UTC, derevnjuk commented on packages/openapi-sampler/src/samplers/Sampler.ts
> +export type SamplerSchema = OpenAPIV3.SchemaObject | OpenAPIV2.SchemaObject;
```suggestion
export type OpenAPISchema = OpenAPIV3.SchemaObject | OpenAPIV2.SchemaObject;
```

2021-05-14 12:26 UTC, mvhysko commented on packages/capture/tsconfig.spec.json
> +{
I thought it would be better to keep them in one place

2021-05-14 16:22 UTC, derevnjuk commented on packages/capture/tsconfig.spec.json
> +{
I don't think so, three config file in one place is too much)

2021-05-17 11:28 UTC, derevnjuk requested changes

2021-05-17 11:28 UTC, derevnjuk commented on package.json
> +    "multi-semantic-release": "^2.8.0",
You should use `@qiwi/multi-semantic-release instead`

2021-05-17 11:28 UTC, derevnjuk commented on .github/workflows/auto-build.yml
> +      - run: npm run test
Revert changes

2021-05-17 11:28 UTC, derevnjuk commented on packages/openapi-sampler/package.json
> +    "test": "cross-env TS_NODE_PROJECT=tests/tsconfig.spec.json mocha -r ts-node/register -r tsconfig-paths/register tests/**/*.spec.ts"
Please remove `.spec` postfix from filename

2021-05-17 11:28 UTC, derevnjuk commented on .github/workflows/auto-build.yml
> +      - run: npm run bootstrap
It won't work, you should issue the following command: `npm ci && lerna bootstrap --hoist`.

2021-05-17 12:31 UTC, derevnjuk requested changes

2021-05-17 12:31 UTC, derevnjuk commented on package.json
> +    "semantic-release": "semantic-release",
I'm not sure, npm will be able to find `@qiwi/multi-semantic-release` by `semantic-release` reference

2021-05-17 12:39 UTC, mvhysko commented on package.json
> +    "semantic-release": "semantic-release",
yes, you are right. Did not notice. thanks

2021-05-17 12:49 UTC, derevnjuk approved these changes

2021-05-18 06:36 UTC, derevnjuk commented on .prettierignore
> +**/tests
Why did you exclude tests?

2021-05-18 06:38 UTC, derevnjuk commented on package.json
> +    "@types/node": "^15.3.0",
If I'm not mistaken, we agreed to use Node.js v14

2021-05-19 08:10 UTC, derevnjuk approved these changes

2021-05-19 08:11 UTC, derevnjuk commented on .github/workflows/auto-build.yml
> +      - run: npm ci && lerna bootstrap
Why did you decide to disable `hoist`?

2021-05-19 09:48 UTC, mvhysko commented on .github/workflows/auto-build.yml
> +      - run: npm ci && lerna bootstrap
Well. There is an issue with `@types/node` in `oas` package and I found only this way to fix it. `oas` package requires the `@types/node` but with `--hoist` it can not find this dependency in the root `node_models`. Tell me pls, if you know how to solve this problem.

2021-05-19 21:10 UTC, merged