feat(core): introduce a new core package
NeuraLegion/har-sdk pull request #34
Opened 2021-11-16 13:48 UTC by derevnjuk

closes #29

2021-11-16 19:11 UTC, pmstss commented on packages/validator/package.json
> +    "oas",
i would add `openapi` as keyword as well

2021-11-16 19:53 UTC, pmstss requested changes
noop first.spec.ts

2021-11-16 19:53 UTC, pmstss commented on packages/core/src/importers/OASV3Importer.ts
> +  private readonly SUPPORTED_OPENAPI_VERSION = /^3\.\d+\.\d+$/; // 3.x.x
`validator` package supports only 3.0.x :/

2021-11-16 19:53 UTC, pmstss commented on packages/core/tests/OASV2Importer.spec.ts
> +    it('should refuse to support of an incompatibility version', () => {
```suggestion
    it('should refuse to support of an incompatible version', () => {
```

2021-11-16 19:53 UTC, pmstss commented on packages/core/tests/HARImporter.spec.ts
> +    it('should refuse to support of an incompatibility version', () => {
```suggestion
    it('should refuse to support of an incompatible version', () => {
```

2021-11-16 19:53 UTC, pmstss commented on packages/core/tests/OASV3Importer.spec.ts
> +    it('should refuse to support of an incompatibility version', () => {
```suggestion
    it('should refuse to support of an incompatible version', () => {
```

2021-11-16 19:53 UTC, pmstss commented on packages/core/tests/PostmanImporter.spec.ts
> +    it('should refuse to support of an incompatibility version', () => {
```suggestion
    it('should refuse to support of an incompatible version', () => {
```

2021-11-16 19:53 UTC, pmstss commented on packages/core/tests/first.spec.ts
> +  it('should be resolved with an undefined if all promises are rejected');
missing test cases code?

2021-11-16 19:53 UTC, pmstss commented on packages/core/README.md
> +const result = await new SpecExplorer().tryToImportSpec(petstore);
i'm not a fan of current naming (both for class and method), but have no better ideas atm

2021-11-16 22:41 UTC, derevnjuk commented on packages/core/README.md
> +const result = await new SpecExplorer().tryToImportSpec(petstore);
Yeah, me too. We can discuss this point

2021-11-16 22:47 UTC, derevnjuk commented on packages/core/tests/first.spec.ts
> +  it('should be resolved with an undefined if all promises are rejected');
Nope, this is a pending test (aka todo). Use them to define tests cases, later you can back and implement them, knowing that you don't forget anything

2021-11-17 12:38 UTC, pmstss approved these changes

2021-11-17 12:44 UTC, merged