feat(validator): har-sdk validator initial
NeuraLegion/har-sdk pull request #7
Opened 2021-06-07 15:37 UTC by mvhysko

closes #6

2021-06-07 15:59 UTC, derevnjuk commented on packages/validator/README.md
> +## Usage
Well, it seems there's lack of documentation)

2021-06-08 14:47 UTC, derevnjuk requested changes
Please cover by unit-tests `validator`, each edge case should be described. See details in [our KB](https://kb.neuralegion.com/#/guide/np-web-ui/scanning/discovery-types/troubleshooting?id=openapiswagger-schema-validation-checklist).

2021-06-08 14:47 UTC, derevnjuk commented on packages/oas/tsconfig.json
> +      "path": "../validator/tsconfig.json"
You should specify a path to the directory which contains tsconfig.json. TSC will be able to find them by itself

2021-06-09 17:55 UTC, mvhysko commented on packages/validator/README.md
> +## Usage
added short documentation.

2021-06-10 06:55 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +describe('OpenApi', async () => {
Please follow test suites/cases naming convention.

- **Unit tests**:

```ts
describe('Class name', () => {
  describe('method name', () => {
    it('should do someting', () => {
       // code
    });
  })
})
```

_Example_: see above

- **e2e/integration**:

```ts
describe('Operation name', () => {
  describe('somehow', () => {
    it('should do someting', () => {
       // code
    });
  })
})
```

_Example_:

```ts
describe('Run repeater', () => {
  describe('with --daemon option', () => {
    it('should run repeater in deamon mode', () => {
       // code
    });
  })
})
```

2021-06-10 07:04 UTC, derevnjuk requested changes

2021-06-10 07:04 UTC, derevnjuk commented on packages/validator/schemas/openapi/v3.0.0.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
Swagger 2 is based on the types supported by the draft-5 (aka Wright 00).

2021-06-10 07:04 UTC, derevnjuk commented on packages/validator/src/validator/DefaultValidator.ts
> +export class DefaultValidator implements Validator {
You should extract logic to validate Postman and OAS to two separate classes. Otherwise, it will be pretty hard to maintain such spaghetti code.

2021-06-10 07:04 UTC, derevnjuk commented on packages/validator/src/validator/DefaultValidator.ts
> +    if (!validate(document)) {
You should use async version of this function

2021-06-10 07:44 UTC, derevnjuk requested changes

2021-06-10 07:44 UTC, derevnjuk commented on packages/validator/src/validator/DefaultValidator.ts
> +    addFormats(this.ajv);
Add only these formats/keywords which are really used. That might allow us to minimize bundle size. I propose you use `rollup-plugin-visualizer` to see the difference.

2021-06-14 07:12 UTC, derevnjuk commented on packages/validator/package.json
> +  "main": "dist/index.js",
What is the reason to use `rollup` if you provide only es2015 module?

2021-06-16 18:32 UTC, derevnjuk requested changes

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/src/validator/OASValidator.ts
> +  private readonly VERSION_SCHEMA_MAP = {
```suggestion
  private readonly VERSION_SCHEMA_MAP: Readonly<Record<2 | 3, string>> = {
```

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/src/validator/PostmanValidator.ts
> +  // ];
Remove redundant comments

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/src/validator/PostmanValidator.ts
> +    return document.info.schema ? parse(document.info.schema).dir + '/' : '';
The preferred way is using template strings. BTW that's not path anyway, you can't use `path` module

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/src/validator/Validator.ts
> +  errors: Partial<ErrorObject>[];
Extend interface by adding `status` field

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +// import githubSwagger from './petstore_swagger.json';
Remove useless comments

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +import githubSwagger from './github_swagger.json';
Please follow naming convention, we don't use lodash in filenames

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +      console.log(result.errors);
`console.log` is forbidden for a reason, remove it

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +  describe('verify', async () => {
ditto

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +    });
This test is duplicate of previous one

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +    it('V2 invalid JSON: cannot determine version of document', async () => {
Follow naming convention, https://github.com/NeuraLegion/har-sdk/pull/7#discussion_r648900275

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +import { expect } from 'chai';
use `should` instead of `expect`, see example in nexploit-service

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/tests/tsconfig.json
> +  "include": ["src", "schemas", "tests"]
Which `tests` it should include? This config is in `tests` folder) Also, why don't use `tsconfig.json` of the package itself?

2021-06-16 18:32 UTC, derevnjuk commented on packages/validator/src/validator/OASValidator.ts
> +  }
Are really need an entire method to load schemas? Why don't pass them via constructor?
```suggestion
  constructor() {
    super([schemaV2, schemaV3]);
  }
```

2021-06-17 11:46 UTC, mvhysko commented on packages/validator/src/schemas/postman/v2.0.0.json
> +  "$async": true,
Do you mean to put comment in schema?

2021-06-17 11:51 UTC, mvhysko commented on packages/validator/src/validator/Validator.ts
> +  errors: Partial<ErrorObject>[];
Do you mean this?:
```ts
enum Status {
  SUCCESS = 'success',
  FAIL = 'fail'
}
```

2021-06-17 11:58 UTC, mvhysko commented on packages/validator/tests/oas.spec.ts
> +    });
Well, the error message is equal but the schemas are different.

2021-06-17 13:34 UTC, derevnjuk commented on packages/validator/src/schemas/postman/v2.0.0.json
> +  "$async": true,
Yeah you're right

2021-06-17 13:36 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +    });
In such way, you should adjust error message

2021-06-17 13:37 UTC, derevnjuk commented on packages/validator/src/validator/Validator.ts
> +  errors: Partial<ErrorObject>[];
It doesn't matter, you can add `valid` flag too

2021-06-22 08:59 UTC, derevnjuk approved these changes

2021-06-22 08:59 UTC, derevnjuk commented on packages/validator/tests/postman.spec.ts
> +    it('Should throw error - invalid document', async () => {
```suggestion
    it('should throw error if document is invalid', async () => {
```

2021-06-22 08:59 UTC, derevnjuk commented on packages/validator/tests/postman.spec.ts
> +    it('Should throw error - cannot determine version of document', async () => {
ditto

2021-06-22 08:59 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +    it('should throw error - must have required property url', async () => {
ditto

2021-06-22 08:59 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +    it('should throw error - must have required property servers', async () => {
ditto

2021-06-22 08:59 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +    it('should throw error - must have required property host', async () => {
ditto

2021-06-22 08:59 UTC, derevnjuk commented on packages/validator/tests/oas.spec.ts
> +    it('should throw error - Cannot determine version of schema. Schema ID is missed.', async () => {
ditto

2021-06-22 20:55 UTC, merged